name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          prune-cache: false

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run unit tests
        run: >
          uv run pytest
          --timeout=10
          --color=yes
          --verbose --verbosity=10 --capture=no --tb=native --showlocals 

      - name: Run unit tests for examples
        run: >
          uv run pytest examples/team_recommender/tests/*.py
          --timeout=10
          --color=yes
          --verbose --verbosity=10 --capture=no --tb=native --showlocals

      - name: Run all tests for example 1
        run: >
          uv run pytest examples/team_recommender/tests/example_1_text_response
          --timeout=10
          --color=yes
          --verbose --verbosity=10 --capture=no --tb=native --showlocals
          -k "not test_compute_alignment and not test_reproducing_the_same_text_embedding and not test_response_shows_developer_names and not test_llm_will_hallucinate_given_no_data and not test_cosine_similarity_generated_responses"

      - name: Type check
        run: uv run mypy src tests examples/team_recommender/src

      - name: Linter and formatter
        run: |
          uv run ruff check src tests examples
          uv run ruff format src tests examples

      - name: Check package build
        run: uv build --verbose
